---
title: "Figure 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data

```{r}
library(Seurat)
library(dplyr)
library(patchwork)

sce <- readRDS("GSE333464_scRNAseq_mouse_PLA2G2D.rds")
```

# Fig4H

```{r}
DimPlot(sce, group.by = "celltype", label = TRUE, cols = sce@meta.data$color_vectors$celltype) + NoLegend()
```

# Fig4I

```{r}
p1 <- VlnPlot(object = sce, features = 'Pla2g2d', group.by = "celltype", log = T) + NoLegend()
print(p1)
```

# Fig4J

```{r}
genes <- c("Cd79a", "Ms4a1", "Cd3e", "Cd8a", "Cd4", "Foxp3", "Rorc", "S100a9", "Csf3r", "Csf2rb", "Zbtb46", "Klrb1c", "Stmn1", "Siglech", "Batf3", "H2-Aa", "Cd68", "Csf1r", "Ccr2", "Fcgr1", "Itgam", "Pla2g2d", "Cd209b", "C1qa", "Nr1h3", "Apoe")

avg <- AverageExpression(
  sce,
  group.by = "celltype",
  features = genes
)$RNA

gene_order <- hclust(dist(avg))$order
genes_clustered <- rownames(avg)[gene_order]

avg_scaled <- t(scale(t(avg)))
gene_order <- hclust(dist(avg_scaled))$order
genes_clustered <- rownames(avg_scaled)[gene_order]

celltype_order <- hclust(dist(t(avg)))$order
celltypes_clustered <- colnames(avg)[celltype_order]

sce$celltype <- factor(
  sce$celltype,
  levels = celltypes_clustered
)

dittoDotPlot(sce, 
             vars = genes_clustered,
             group.by = "celltype") + coord_flip() +
  scale_color_gradient2(
  low = "#2166AC",
  mid = "#F7F7F7",
  high = "#B2182B",
  midpoint = 0)
```

# Fig4K

```{r}
library(ggplot2)
library(ggpubr)
library(dplyr)

# Calculate cell proportions

meta <- sce@meta.data
head(meta)

counts <- meta %>%
  group_by(tissue, celltype) %>%
  summarise(n = n()) %>%
  ungroup()

ratios <- meta %>%
  group_by(orig.ident, celltype, tissue) %>%
  summarise(n = n()) %>%
  tidyr::pivot_wider(names_from = celltype, values_from = n, values_fill = 0) %>%
  mutate(ratio = LNM / (LNM + TAM + DC + moDC + pDC))

# visualise

comparisons <- list(
  c("Tumor", "TDLN"),
  c("LN", "TDLN"),
  c("LN", "Tumor")
)

p1 <- ggplot(ratios, aes(x = tissue, y = ratio, fill = tissue)) +
  geom_boxplot(alpha = 0.6, outlier.shape = NA) +
  geom_jitter(width = 0.15, size = 2, alpha = 0.8) +
  theme_classic(base_size = 14) + 
  labs(
    title = "LNMs",
    y = "% LNMs of myeloid cells",
    x = "Tissue"
  ) +
  #scale_y_continuous(trans='log10') +
   stat_compare_means(comparisons = comparisons, method = "t.test", label = "p.signif") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "none"                             
  )

print(p1)
```

# Fig4L

```{r, fig.width=3, fig.height=4}
VlnPlot(merged, features = "Pla2g2d", group.by = "tissue", log = T)
```

# Fig4M

```{r}
#https://rpubs.com/IL2/514990

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install(c("dplyr", 
                       "clusterProfiler", 
                       "msigdbr", 
                       "enrichplot",
                       "org.Hs.eg.db", 
                       "org.Mm.eg.db", 
                       "bioma"
                       ))

library(dplyr)
library(msigdbr)
library(clusterProfiler)
library(org.Mm.eg.db)
library(enrichplot)

####### Preparing the data #############################################################
##  Import your DEG data containing log2fold changes
    df <- read.delim("DSP_LMM_DFxR.txt", row.names = 1, quote = "")
    df <- subset(df, Subset == "CD68")

##  Select only your GeneIDs and your Log2F
    df <- df[, grepl("Gene", names(df)) | grepl("Estimate", names(df))]
    colnames(df) <- c("GeneID", "LogF2")
    
  df$LogF2 <- df$LogF2 *-1

##  feature 1: LOGF2
    geneList <- df$LogF2

##  feature 2: named vector
    names(geneList) <- df$GeneID

##  feature 3: decreasing order
    geneList <- sort(geneList, decreasing = TRUE)
    head(geneList)
    class(geneList) #should be numeric

##  Create a LogF2 cut-off e.g. > 1
    gene <- geneList[abs(geneList) > 0] #Change log2fold cutoff here
    head(gene)
    
    

####### Creating a custom pathway #############################################################
##  Make a tab-delimited file for your custom pathways
##  [First column: name of pathway][Following columns: genes belonging to pathway]
## !!! Make sure this is in the right species format !!!

    path <- read.delim("P044_LN_TDLN_CelltypeMarkers.txt", header = T, row.names = 1)
    path <- subset(path, cluster == "LAM" & p_val_adj < 0.05 & avg_log2FC > 1)
    path <- na.omit(path)
    path <- data.frame(path = print("LAM"),
                       gene = path$gene)
    
        
convert_mouse_to_human <- function(gene_list) {

  mouse_human_genes <- read.delim(
    "https://www.informatics.jax.org/downloads/reports/HOM_MouseHumanSequence.rpt"
  )

  sapply(gene_list, function(gene) {
    class_key <- mouse_human_genes %>%
      dplyr::filter(Symbol == gene,
                    Common.Organism.Name == "mouse, laboratory") %>%
      dplyr::pull(DB.Class.Key)

    if (length(class_key) == 0) return(NA)

    mouse_human_genes %>%
      dplyr::filter(DB.Class.Key == class_key,
                    Common.Organism.Name == "human") %>%
      dplyr::pull(Symbol) %>%
      .[1]   # take first match only
  })
}

path$gene <- convert_mouse_to_human(path$gene)
path <- unique(path)

table(names(geneList) %in% path$gene)

####### Running the GSEA #############################################################

    em <- GSEA(geneList = geneList,  
                    exponent = 1, #standard
                    minGSSize = 0, #Minimum amount of genes in one geneset
                    maxGSSize = 10000, #Maximum amount of genes in one geneset
                    pAdjustMethod = "BH", 
                    TERM2GENE = path, #genesets
                    pvalueCutoff = 1, #put 1 to see all pathways
                    verbose = TRUE)
 
##  Save your GSEA output
    setwd("YOUR_PATH") #where you will write your file

    head(as.data.frame(cbind(em@result$ID, em@result$pvalue, em@result$p.adjust, em@result$NES)))
    xy <- as.data.frame(cbind(em@result$ID, em@result$pvalue, em@result$p.adjust, em@result$NES))
    colnames(xy) <- c("Pathway", "P-value", "Adj. P-value", "NES")
    write.table(xy, "FILENAME.txt", sep = "\t", row.names = F, col.names = T)

####### Plotting your GSEA analysis #############################################################

## Run the function
        GSEAplot<-function(x){
          gseaplot2(x = em, 
                    geneSetID =x,
                    base_size = 20,
                    rel_heights = c(1.5, 0.5, 1),
                    title=em$ID[x],
                    color="red",
                    subplots = 1:3,
                    ES_geom = "line",
                    pvalue_table=T)
        }
    
    GSEAplot(1)
      
## Save your GSEA plot

        filename <- paste0("GSEA_LAM.pdf")

        pdf(file = filename, width = 10, height = 9)
        GSEAplot(1)
        dev.off()
 
```

# Fig4N

```{r, fig.height=7, fig.width=6}

x <- subset(merged, (celltype == "LAM"))

expr <- FetchData(x, vars = gene)[,1]
x$pla_status <- ifelse(expr > 0, "Pla2g2d+", "Pla2g2d-")

Idents(x) <- x$pla_status
table(x$pla_status)

markers <- FindMarkers(LNM, group.by = "pla_status", ident.1 = "Pla2g2d+", ident.2 = "Pla2g2d-")

write.table(markers, "P044_clusterMarkers_LAM_plapos_vs_planeg.txt", sep = "\t")


library(EnhancedVolcano)
   
      ##### Define custom colors #####
      # set the base colour as grey
      keyvals <- rep('#d3d3d3', nrow(markers))

      #set the base name/label as 'NS'
      names(keyvals) <- rep('NS', nrow(markers))

      # modify keyvals for variables with fold change > 1 and Padj < 0.05
      keyvals[which(markers$avg_log2FC > 0.4 &
                      markers$p_val_adj < 0.05)] <- '#ba181b' #color code
      names(keyvals)[which(markers$avg_log2FC > 0.4 &
                             markers$p_val_adj < 0.05)] <- 'Pla2g2d+' #Upregulated genes
      
            # modify keyvals for variables with fold change > 1 and Padj < 0.05
      keyvals[which(markers$avg_log2FC < -0.4 &
                      markers$p_val_adj < 0.05)] <- '#023e8a' #color code
      names(keyvals)[which(markers$avg_log2FC < -0.4 &
                             markers$p_val_adj < 0.05)] <- 'Pla2g2d-' #Upregulated genes
      
      genes = c("Gpm6b", "Cd4", "Rxrg", "Cxcr2", "Apoe", "Lyz2", "Il4i1", "Cd63", "Il22ra2", "Nr1h3", "Timd4", "Trem2", "Spp1", "Adgre1", "Ccr2", "Pla2g2d")
      
      genes[!genes %in% rownames(markers)]
      
      volcano <- EnhancedVolcano(markers,
                           lab = rownames(markers),         # Labels of your points
                           title = "LNM - Pla2g2d+ vs Pla2g2d-",                # Title of your volcanoplot
                           x = "avg_log2FC",            # What to plot on the x-axis
                           y = "p_val_adj",         # What to plot on the y-axis
                           pCutoff = 0.05,            # Adj. P-value cutoff
                           FCcutoff = 0.4,              # Fold change cutoff
                           selectLab = genes,          # Write down comma delimited genes to only show these genes
                           drawConnectors = TRUE,     # Draw a connecting line to your label
                           #max.overlaps = Inf,  
                           #arrowheads = F,           # Whether the connectors should have a arrowhead
                           #widthConnectors = 0.1,    # How thick the line of the connectors should be
                           #colConnectors = "black",  # Colour of the connectors
                           #boxedLabels = TRUE,       # Draw a box around your label
                           #legendVisible = F,        # standard is TRUE
                           colAlpha = 0.6,            # transparency of points
                           #xlim = c(-13, 20),      # change axis range
                           #ylim = c(0,30),           # change axis range
                           pointSize = 3,             # Define size of the dots
                           labSize = 4,            # Define size of the labels
                           gridlines.minor = FALSE,   # Add minor grid to background
                           gridlines.major = FALSE,   # Add major grid to background
                           cutoffLineType = 'dashed',  # Add cutoff lines for Log2Fold/Pval. 
                           cutoffLineCol = "#d3d3d3", # Colour of the cutoff line
                           border = "full",           # Chose "full", "partial" or "blank"
                           borderColour = "black",
                           borderWidth = 0.5,
                           colCustom = keyvals #Add custom colors for your values as defined above 
                           ) #+ coord_flip() #Flip the volcanoplot on its side
    
  
    pdf("volcano_LNM_plapos_vs_planeg.pdf", width = 10, height = 8)
    print(volcano)
    dev.off()
    
```

# Fig4O

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

#BiocManager::install("biomaRt")
library("biomaRt")


geneSet <- read.delim("TMZ_immunity-2017.txt")
gs.ls <- as.list(geneSet)

# check if genes are in list

genes_in_seurat <- rownames(merged)
filtered_list <- lapply(gs.ls, function(gene_vec) {
  gene_vec[gene_vec %in% genes_in_seurat]
})

lengths(filtered_list)
min_genes <- 5
filtered_list <- filtered_list[lengths(filtered_list) >= min_genes]

merged <- AddModuleScore(object = merged, 
                         features = filtered_list, 
                         name = paste0("Score_", names(filtered_list)), 
                         ctrl = 5, 
                         seed = 291225)

# Plot

score_features <- grep("Score", colnames(merged@meta.data), value = TRUE)
score_features

VlnPlot(object =  subset(merged, (tissue == "TDLN" | tissue == "LN") & (lineage == "Macrophage" | lineage == "DC")), 
        features = score_features , group.by = "celltype") + NoLegend()


pdf("Score_TMZ_signature.pdf", width = 5, height = 5)
FeaturePlot(merged, features = "Score_TMZ_signature1", order = T, min.cutoff = "q10")
dev.off()

```

# Fig4P

```{r, fig.width=4, fig.height=5}
# Load libraries
library(Seurat)
library(ggplot2)
library(ggpubr)
library(dplyr)

# Choose your gene of interest
gene_of_interest <- "Score_TMZ_signature1"

# Extract expression values and metadata
expr_data <- FetchData(x, vars = c(gene_of_interest, "celltype", "pla_status"))
colnames(expr_data) <- c("expression", "celltype",  "pla_status")

# Define your custom color palette (16 distinct colors)
my_colors <- c(
  "#1f77b4", "#ff7f0e")

# Make sure colors correspond to your celltype order
# (optional, ensures consistent mapping)
names(my_colors) <- levels(factor(expr_data$pla_status))

# Basic boxplot using ggplot2 with custom colors
p <- ggplot(expr_data, aes(x = pla_status, y = expression, fill = pla_status)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.8) +
  geom_jitter(width = 0.2, size = 1.5, alpha = 0.5) +
  scale_fill_manual(values = my_colors) +             # <-- your custom palette
  #scale_y_log10() +
  labs(
    title = paste("ModuleScore TZM Signature"),
    x = "Cell Type",
    y = expression(paste("log"[10], "(Expression)"))
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  ) +
  facet_wrap(~celltype)

# Add statistical test results (pairwise Wilcoxon tests)
pdf("ModuleScore_TZM_Boxplots_Macs.pdf", width = 4, height = 5)
p + stat_compare_means(
  method = "wilcox.test",
  label = "p.signif", comparisons = list(c("Pla2g2d+", "Pla2g2d-")))
dev.off()
```

# Fig4Q

```{r}
x <- subset(sce, celltype == "CD8T")
Idents(x) <- x$treatment
markers <- FindMarkers(x, ident.1 = "aPLA2G2D", ident.2 = "untreated", min.pct = 0)

library(EnhancedVolcano)
   
      ##### Define custom colors #####
      # set the base colour as grey
      keyvals <- rep('#d3d3d3', nrow(markers))

      #set the base name/label as 'NS'
      names(keyvals) <- rep('NS', nrow(markers))

      # modify keyvals for variables with fold change > 1 and Padj < 0.05
      keyvals[which(markers$avg_log2FC > 0 &
                      markers$p_val_adj < 0.05)] <- '#ba181b' #color code
      names(keyvals)[which(markers$avg_log2FC > 0 &
                             markers$p_val_adj < 0.05)] <- 'aPLA2G2D' #Upregulated genes
      
            # modify keyvals for variables with fold change > 1 and Padj < 0.05
      keyvals[which(markers$avg_log2FC < 0 &
                      markers$p_val_adj < 0.05)] <- '#023e8a' #color code
      names(keyvals)[which(markers$avg_log2FC < 0 &
                             markers$p_val_adj < 0.05)] <- 'untreated' #Upregulated genes
      
      genes <- c("Ccl5", "Runx2", "Ccl4", "Ccr5", "Gzmb", "Cxcr3", "Ctla2a", "Fasl", "Ifng", "Lag3", "Pdcd1", "Klrc1", "Id2", "Entpd1", "Ifngr1", "Tbx21", "Bhlhe40", "Nkg7", "Il2rb", "Cd44", "Eomes", "Slamf7", "Ccr9", "Tsc22d3")
             
      volcano <- EnhancedVolcano(markers,
                           lab = rownames(markers),         # Labels of your points
                           title = "CD8T - Unt vs aPLA",                # Title of your volcanoplot
                           x = "avg_log2FC",            # What to plot on the x-axis
                           y = "p_val_adj",         # What to plot on the y-axis
                           pCutoff = 0,            # Adj. P-value cutoff
                           FCcutoff = 0,              # Fold change cutoff
                           selectLab = genes,          # Write down comma delimited genes to only show these genes
                           drawConnectors = TRUE,     # Draw a connecting line to your label
                           max.overlaps = Inf,  
                           boxedLabels = TRUE,       # Draw a box around your label
                           colAlpha = 0.6,            # transparency of points
                           xlim = c(-5, 5),      # change axis range
                           pointSize = 3,             # Define size of the dots
                           labSize = 4,            # Define size of the labels
                           gridlines.minor = FALSE,   # Add minor grid to background
                           gridlines.major = FALSE,   # Add major grid to background
                           cutoffLineType = 'dashed',  # Add cutoff lines for Log2Fold/Pval. 
                           cutoffLineCol = "#d3d3d3", # Colour of the cutoff line
                           border = "full",           # Chose "full", "partial" or "blank"
                           borderColour = "black",
                           borderWidth = 0.5,
                           colCustom = keyvals #Add custom colors for your values as defined above 
                           )
    
  
    print(volcano)
```
